apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: szbk35o7e-python 
  janus-idp.io/tekton: szbk35o7e-python
  backstage.io/kubernetes-id: szbk35o7e-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: szbk35o7e-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  